### ISSUE TITLE
Initial Requirements for POC1

### ISSUE THREAD

**Issue by sierra-tango-echo** [openflighthpc/flight-message#1]
Make an asset notification handler kthxbye

**Comment by sierra-tango-echo** [comment]
ideas:
[davidwarethoughts.pdf](https://github.com/openflighthpc/flight-message/files/3120846/davidwarethoughts.pdf)

**Comment by sierra-tango-echo** [comment]
example data templates:
[notifications.zip](https://github.com/openflighthpc/flight-message/files/3120868/notifications.zip)

**Comment by sierra-tango-echo** [comment]
POC1 release deliverables:

- Create / Delete notifications of both types for any asset
- Parse & Reap (delete expired/duplicated notifications etc) and display all asset notifications, or notifications for a particular asset

Brownie points available for:
 - logging
 - `etc/` config file for configurable data paths etc
 - install integration with flight runway etc

Prizes for the winning entry TBC

**Comment by sierra-tango-echo** [comment]
@DavidMarchant 4 u

**Comment by sierra-tango-echo** [comment]
apparently this is gonna take 7 minutes 🤨

**Comment by sierra-tango-echo** [comment]
time starts now

**Comment by mjtko** [comment]
And thus, we now know that 86,400 mins = 7 @DavidMarchant minutes (DMM), and that there are \~12,343 minutes (\~= 8.57 earth days) per DMM.

**Comment by DavidMarchant** [comment]
good things come to those who wait :roll_eyes:

**Comment by sierra-tango-echo** [comment]
does this though..

![Screenshot 2019-06-25 at 16 28 38](https://user-images.githubusercontent.com/503613/60111799-87a97980-9766-11e9-90ce-9c6890f115d9.png)

❤️
